// worker-configuration.d.ts (generated by `wrangler types`) is already part of
// the TypeScript program via tsconfig.json's "include" — this just merges into
// its `Cloudflare.Env` interface, no explicit reference needed.
declare namespace Cloudflare {
  interface Env {
    RESEND_API_KEY?: string;
    EMAIL_FROM?: string;
    TURNSTILE_SECRET_KEY?: string;
    TURNSTILE_SITE_KEY?: string;
  }
}
