// worker-configuration.d.ts (generated by `wrangler types`) is already part of
// the TypeScript program via tsconfig.json's "include" — this just merges into
// its `Cloudflare.Env` interface, no explicit reference needed.
declare namespace Cloudflare {
  // No server env vars are currently required — the site is fully static
  // (front door = WhatsApp/email links; donations = outbound PayPal link).
  // Re-add secrets here if a server-side integration returns.
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface Env {}
}
